name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    container:
      image: python:3.11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install semgrep pip-audit

      # =========================
      # SAST (Semgrep)
      # =========================
      - name: Run Semgrep (SAST)
        run: |
          semgrep scan --config auto --severity ERROR --error .

      # =========================
      # Dependency Security (pip-audit)
      # =========================
      - name: Run pip-audit (SCA)
        run: |
          pip-audit --desc

      # =========================
      # Infrastructure / File Scan (Trivy)
      # =========================
      - name: Install Trivy
        run: |
          apt-get update
          apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy FS Scan
        run: |
          trivy fs . \
            --severity HIGH,CRITICAL \
            --exit-code 1
